### ISSUE TITLE
Unable to build nor run the program on Linux

### ISSUE THREAD

**Issue by Stargazer3240** [trumank/drg-mod-integration#92]
Hello, I'm under Linux (Fedora 38 with GNOME) and I'm unable to run the mod integration binary nor do a cargo build in the source code. The error are the following, plus the output that `rustup show` gives:
[Error Bin](https://pastebin.com/XyJnRFDt)
[Rustup Show](https://pastebin.com/FZWMD1zf)
[Error Build](https://pastebin.com/jG4vYnbm)

**Comment by trumank** [comment]
The latest release ended up accidentally dynamically linking to `libssl` and was fixed in #ec75ebf63d3d9901b5fdd56a4fe7f442b14b8554.

I'm not familiar with Fedora but it looks like all you need to do is install the glib2 dev dependency to compile the latest commit: https://unix.stackexchange.com/a/648187

**Comment by Stargazer3240** [comment]
Thanks for the fast response! After installing glib2, I need to add the windows target for Rust. After that, it gave an error that it couldn't find `gdk-3.0`, so I installed all the developers dependencies for Gtk (in the case of [Fedora](https://developer.fedoraproject.org/tech/languages/c/gtk.html)). After that, I had to install `mingw64-gcc` and was finally able to compile the project!

**Comment by jcotton42** [comment]
Could we get a new binary release with this fix? In particular the dependency on libssl breaks the binary on SteamOS.

**Comment by Dr01000111** [comment]
Hey im still getting this issue under nobara linux (a fork of fedora) and the above fixes are not working for me

**Comment by stargazer3240** [comment]
> Hey im still getting this issue under nobara linux (a fork of fedora) and the above fixes are not working for me

I'll give a breakdown of what you should do, hope it works.

- Install these requirements: `sudo dnf install glib2-devel mingw64-gcc gtk3-devel gstreamer1-devel clutter-devel webkit2gtk3-devel libgda-devel gobject-introspection-devel`
- Then install `rustup`. You can install either with the official script or through dnf, I did the latter ( `sudo dnf install rustup`).
- If you have previously installed `rust` and `cargo` through dnf, remove them and then run `rustup-init`.
- The defaults for the init script should be fine. After you ran `source "$HOME/.cargo/env"` or reopened your terminal, go to the `mint` directory you downloaded/cloned and run `cargo build --release`. 
- Finally, after compiling everything, your executable will be at `./target/release/mint`.
